name: Build Haproxy for ARM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up cross-compilation environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-arm-linux-gnueabihf \
            binutils-arm-linux-gnueabihf \
            make \
            docker.io \
            libssl-dev \
            zlib1g-dev \
            libpcre3-dev \
            autoconf \
            libtool \
            wget \
            git \
            g++
          
          # 清理不必要的软件包
          sudo apt-get -y autoremove
          sudo apt-get clean

      - name: Download OpenSSL
        run: |
          wget https://www.openssl.org/source/openssl-1.1.1q.tar.gz
          tar -xvzf openssl-1.1.1q.tar.gz
          cd openssl-1.1.1q && ./config --prefix=/opt/openssl no-shared
          make && make install

      - name: Download Zlib
        run: |
          # 下载最新版本的 Zlib 从 GitHub Releases
          ZLIB_VERSION=1.2.12
          curl -LO https://github.com/madler/zlib/archive/refs/tags/${ZLIB_VERSION}.tar.gz
          tar -xvzf ${ZLIB_VERSION}.tar.gz
          cd zlib-${ZLIB_VERSION} && ./configure --static
          make && make install

      - name: Download PCRE
        run: |
          wget https://ftp.pcre.org/pub/pcre/pcre-8.44.tar.gz
          tar -xvzf pcre-8.44.tar.gz
          cd pcre-8.44 && ./configure --prefix=/opt/pcre --disable-shared
          make && make install

      - name: Build Haproxy for ARMv7
        run: |
          wget https://www.haproxy.org/download/2.7/src/haproxy-2.7.0.tar.gz
          tar -xvzf haproxy-2.7.0.tar.gz
          cd haproxy-2.7.0
          make TARGET=linux2628 ARCH=armv7l USE_PCRE=1 USE_ZLIB=1 USE_OPENSSL=1 STATIC=1
          make install

      - name: Upload Haproxy binaries
        uses: actions/upload-artifact@v3
        with:
          name: haproxy-arm-binaries
          path: ./haproxy-2.7.0/haproxy  # 假设编译后的二进制文件路径
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./haproxy-2.7.0/haproxy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
